/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.sistemauniversidadeead.view;

import br.com.senac.sistemauniversidadeead.model.Curso;
import br.com.senac.sistemauniversidadeead.model.Professor;
import br.com.senac.sistemauniversidadeead.model.Turma;
import br.com.senac.sistemauniversidadeead.model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.senac.sistemauniversidadeead.dao.CursoDAO;
import br.com.senac.sistemauniversidadeead.dao.ProfessorDAO;
import br.com.senac.sistemauniversidadeead.dao.TurmaDAO;
import java.util.List;

/**
 *
 * @author Pichau
 */
public class TelaTurmas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaTurmas.class.getName());

    /**
     * Creates new form TelaCursos
     */
private Usuario usuarioLogado;

private CursoDAO cursoDAO = new CursoDAO();
private ProfessorDAO professorDAO = new ProfessorDAO();
private TurmaDAO turmaDAO = new TurmaDAO();

    public TelaTurmas(Usuario usuario) {
        initComponents();
    this.usuarioLogado = usuario;

    carregarCursos();
    carregarProfessores();
    atualizarTabela();
    }

private void carregarCursos() {

    comboCurso.removeAllItems();

    List<Curso> cursos = cursoDAO.listarCursos();

    for (Curso curso : cursos) {
        comboCurso.addItem(curso.getNome());
    }
}

private void carregarProfessores() {

    comboProfessor.removeAllItems();

    List<Professor> professores = professorDAO.listarProfessores();

    for (Professor professor : professores) {
        comboProfessor.addItem(professor.getNome());
    }
}

    private void limparCampos() {

    txtCodTurma.setText("");
    txtAno.setText("");
    txtPeriodo.setText("");

    if (comboCurso.getItemCount() > 0) {
        comboCurso.setSelectedIndex(0);
    }

    if (comboProfessor.getItemCount() > 0) {
        comboProfessor.setSelectedIndex(0);
    }

    txtCodTurma.requestFocus();
}
    
private void atualizarTabela() {

    DefaultTableModel modelo =
            (DefaultTableModel) tbTurma.getModel();

    modelo.setRowCount(0);

    List<Turma> turmas = turmaDAO.listarTurmas();

    for (Turma turma : turmas) {

        modelo.addRow(new Object[]{
            turma.getId(),
            turma.getCodigo(),
            turma.getPeriodo(),
            turma.getAno(),
            turma.getCurso().getNome(),
            turma.getProfessor().getNome()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodTurma = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTurma = new javax.swing.JTable();
        comboCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboProfessor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setLabelFor(txtCodTurma);
        jLabel2.setText("Código: *");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setLabelFor(txtAno);
        jLabel3.setText("Ano Letivo: *");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Curso Associado: *");

        txtCodTurma.setColumns(8);
        txtCodTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtAno.setColumns(8);
        txtAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tbTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Período", "Ano", "Curso Associado", "Professor Alocado"
            }
        ));
        jScrollPane1.setViewportView(tbTurma);

        comboCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Professor Alocado: *");

        comboProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProfessor.addActionListener(this::comboProfessorActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Período: *");

        txtPeriodo.setColumns(8);
        txtPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Detalhamento da Turma");

        btnSalvar.setBackground(new java.awt.Color(43, 113, 168));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(242, 242, 242));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(204, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        BtnCancelar.setBackground(new java.awt.Color(242, 242, 242));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(this::BtnCancelarActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Turmas Ativas Registradas ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(104, 104, 104))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCodTurma)
                                                .addGap(38, 38, 38)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCancelar))
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProfessor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnExcluir)
                            .addComponent(BtnCancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        TelaPrincipal tela = new TelaPrincipal(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void comboProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProfessorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
   String codigo = txtCodTurma.getText().trim();
    String anoTexto = txtAno.getText().trim();
    String periodo = txtPeriodo.getText().trim();

    if (codigo.isEmpty()
            || anoTexto.isEmpty()
            || periodo.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Preencha todos os campos.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    if (comboCurso.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione um curso.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    if (comboProfessor.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione um professor.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int ano;

    try {

        ano = Integer.parseInt(anoTexto);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "O ano deve ser um número.",
                "Valor inválido",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    String nomeCurso = (String) comboCurso.getSelectedItem();
    String nomeProfessor = (String) comboProfessor.getSelectedItem();

    Curso cursoSelecionado = null;
    Professor professorSelecionado = null;

    List<Curso> cursos = cursoDAO.listarCursos();

    for (Curso curso : cursos) {

        if (curso.getNome().equals(nomeCurso)) {
            cursoSelecionado = curso;
            break;
        }
    }

    List<Professor> professores = professorDAO.listarProfessores();

    for (Professor professor : professores) {

        if (professor.getNome().equals(nomeProfessor)) {
            professorSelecionado = professor;
            break;
        }
    }

    if (cursoSelecionado == null) {

        JOptionPane.showMessageDialog(
                this,
                "Curso selecionado não encontrado.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    if (professorSelecionado == null) {

        JOptionPane.showMessageDialog(
                this,
                "Professor selecionado não encontrado.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    Turma turma = new Turma();

    turma.setCodigo(codigo);
    turma.setAno(ano);
    turma.setPeriodo(periodo);
    turma.setCurso(cursoSelecionado);
    turma.setProfessor(professorSelecionado);

    turmaDAO.cadastrarTurma(turma);

    atualizarTabela();

    JOptionPane.showMessageDialog(
            this,
            "Turma cadastrada com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
    );

    limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tbTurma.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione uma turma para excluir.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int resposta = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir a turma selecionada?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {

        int id = (int) tbTurma.getValueAt(linha, 0);

        turmaDAO.excluirTurma(id);

        atualizarTabela();

        JOptionPane.showMessageDialog(
                this,
                "Turma excluída com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboCurso;
    private javax.swing.JComboBox<String> comboProfessor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbTurma;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCodTurma;
    private javax.swing.JTextField txtPeriodo;
    // End of variables declaration//GEN-END:variables
}
