/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.sistemauniversidadeead.view;

import br.com.senac.sistemauniversidadeead.model.Usuario;
import br.com.senac.sistemauniversidadeead.dao.CursoDAO;
import br.com.senac.sistemauniversidadeead.dao.TurmaDAO;
import br.com.senac.sistemauniversidadeead.dao.ProfessorDAO;
import br.com.senac.sistemauniversidadeead.dao.MatriculaDAO;
import br.com.senac.sistemauniversidadeead.dao.MaterialDAO;

/**
 *
 * @author Pichau
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    private Usuario usuarioLogado;
    private CursoDAO cursoDAO;
    private TurmaDAO turmaDAO;
    private ProfessorDAO professorDAO;
    private MatriculaDAO matriculaDAO;
    private MaterialDAO materialDAO;

    public TelaPrincipal(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;

        cursoDAO = new CursoDAO();
        turmaDAO = new TurmaDAO();
        professorDAO = new ProfessorDAO();
        matriculaDAO = new MatriculaDAO();
        materialDAO = new MaterialDAO();

        lblSessao.setText(
                "Sessão ativa para: " + usuario.getNome()
                + " (" + usuario.getTipo() + ")"
        );

        atualizarIndices();
        configurarPermissoes();
    }

    private void atualizarIndices() {

        numCursos.setText(
                "Cursos: " + cursoDAO.listarCursos().size()
        );

        numTurmas.setText(
                "Turmas: " + turmaDAO.listarTurmas().size()
        );

        numProfessores.setText(
                "Professores: " + professorDAO.listarProfessores().size()
        );

        numMatriculas.setText(
                "Matrículas: " + matriculaDAO.listarMatriculas().size()
        );

        numMateriais.setText(
                "Materiais: " + materialDAO.listarMateriais().size()
        );
    }

    private void configurarPermissoes() {

        switch (usuarioLogado.getTipo()) {

            case DIRETOR:
                // Acesso completo
                break;

            case GESTAO:
                // Acesso completo às funções de cadastro
                break;

            case PROFESSOR:
                // Professor pode acessar apenas Turmas e Materiais
                btnCursos.setEnabled(false);
                btnProfessores.setEnabled(false);
                btnMatriculas.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrincipal = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnTurmas = new javax.swing.JButton();
        btnProfessores = new javax.swing.JButton();
        btnMatriculas = new javax.swing.JButton();
        btnMateriais = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        numMatriculas = new javax.swing.JLabel();
        numMateriais = new javax.swing.JLabel();
        numCursos = new javax.swing.JLabel();
        numTurmas = new javax.swing.JLabel();
        numProfessores = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblSessao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPrincipal.setBackground(new java.awt.Color(242, 242, 242));
        btnPrincipal.setText("Painel Principal");
        btnPrincipal.addActionListener(this::btnPrincipalActionPerformed);

        btnCursos.setBackground(new java.awt.Color(242, 242, 242));
        btnCursos.setText("Cadastrar Cursos");
        btnCursos.addActionListener(this::btnCursosActionPerformed);

        btnTurmas.setBackground(new java.awt.Color(242, 242, 242));
        btnTurmas.setText("Cadastrar Turmas");
        btnTurmas.addActionListener(this::btnTurmasActionPerformed);

        btnProfessores.setBackground(new java.awt.Color(242, 242, 242));
        btnProfessores.setText("Cadastrar Professores");
        btnProfessores.addActionListener(this::btnProfessoresActionPerformed);

        btnMatriculas.setBackground(new java.awt.Color(242, 242, 242));
        btnMatriculas.setText("Cadastrar Matrículas");
        btnMatriculas.addActionListener(this::btnMatriculasActionPerformed);

        btnMateriais.setBackground(new java.awt.Color(242, 242, 242));
        btnMateriais.setText("Cadastrar Materiais");
        btnMateriais.addActionListener(this::btnMateriaisActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SISTEMA UNIVERSIDADE EAD");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        numMatriculas.setText("Matrículas:");

        numMateriais.setText("Materiais:");

        numCursos.setText("Cursos:");
        numCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numCursos.setFocusCycleRoot(true);

        numTurmas.setText("Turmas:");

        numProfessores.setText("Professores:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(numCursos)
                .addGap(18, 18, 18)
                .addComponent(numTurmas)
                .addGap(18, 18, 18)
                .addComponent(numProfessores)
                .addGap(18, 18, 18)
                .addComponent(numMatriculas)
                .addGap(18, 18, 18)
                .addComponent(numMateriais)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCursos)
                    .addComponent(numTurmas)
                    .addComponent(numProfessores)
                    .addComponent(numMatriculas)
                    .addComponent(numMateriais))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PAINEL DE CONTROLE PRINCIPAL");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblSessao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSessao.setText("Sessão ativa para: Fulano da Silva (coordenador)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblSessao)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSessao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTurmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(140, 140, 140))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        TelaCursos tela = new TelaCursos(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurmasActionPerformed
        TelaTurmas tela = new TelaTurmas(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTurmasActionPerformed

    private void btnProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessoresActionPerformed
        TelaProfessor tela = new TelaProfessor(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfessoresActionPerformed

    private void btnMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculasActionPerformed
        TelaMatricula tela = new TelaMatricula(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMatriculasActionPerformed

    private void btnMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaisActionPerformed
        TelaMateriais tela = new TelaMateriais(usuarioLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMateriaisActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnMateriais;
    private javax.swing.JButton btnMatriculas;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnProfessores;
    private javax.swing.JButton btnTurmas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSessao;
    private javax.swing.JLabel numCursos;
    private javax.swing.JLabel numMateriais;
    private javax.swing.JLabel numMatriculas;
    private javax.swing.JLabel numProfessores;
    private javax.swing.JLabel numTurmas;
    // End of variables declaration//GEN-END:variables
}
